FROM quay.io/minio/minio

RUN curl -o /usr/bin/mc https://dl.min.io/client/mc/release/linux-amd64/mc \
    && chmod +x /usr/bin/mc

COPY minio_init.sh /minio_init.sh
RUN chmod +x /minio_init.sh

CMD ["sh", "-c", "minio server /data --console-address ':9090' & sleep 10 && /minio_init.sh && tail -f /dev/null"]
