global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Внутри контейнера Prometheus работает на 9090

  - job_name: 'vov_server'
    static_configs:
      - targets: ['localhost:5000']
    metrics_path: /metrics

  - job_name: 'kafka'
    static_configs:
      - targets: ['localhost:9092']
    metrics_path: /metrics  # Если Kafka не предоставляет метрики, используйте kafka-exporter ниже

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: /_prometheus/metrics

  - job_name: 'minio'
    static_configs:
      - targets: ['localhost:9000']
    metrics_path: /minio/v2/metrics/cluster

  - job_name: 'hasura'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: /metrics